### ISSUE TITLE
Menubar should be under the headbar

### ISSUE THREAD

**Issue by hiunnhue** [Zonnev/elementaryos-firefox#10]
please see the attached screenshot: 

![image](https://user-images.githubusercontent.com/1015601/52899321-ac736a80-3223-11e9-8528-4b68083db6a3.png)

**Comment by Zonnev** [comment]
This is a bug and question I can not fix. The menu bar doesn't separate the tab bar and the header bar like the bookmarks bar does. So moving the menu bar down is pointless, since it doesn't create space for itself pushing other bars away. I tried positioning the menu bar in the tab bar, but it sets before the tab bar buttons, making them not clickable anymore. So, I'm probably not going to fix this, although I would wish to.

**Comment by hiunnhue** [comment]
This works for me: 

```
#nav-bar{
  -moz-box-ordinal-group: 0;
}

#toolbar-menubar {
  -moz-box-ordinal-group: 1;
}
```

**Comment by Zonnev** [comment]
That's a great contribution @hiunnhue ! I thought we couldn't use ordinal groups anymore. I was fiddling with flex direction but it messed up the whole layout. Thanks!
